--SENTENCIA PARA CREAR MODIFICAR Y BORRAR TABLAS
--CREAR UNA TABLA
CREATE TABLE alumno(  
    id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nro_documento VARCHAR(255) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    email VARCHAR(100)
);
--MODFICAR UNA TABLA
ALTER TABLE alumno
ADD COLUMN nota INT DEFAULT 0;

--ELIMINAR UNA TABLA
DROP TABLE alumno;
